# Generated by Django 3.2.4 on 2021-06-17 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerciseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercisedate', models.CharField(max_length=255)),
                ('excercisetype', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'excercisedate',
            },
        ),
        migrations.CreateModel(
            name='ExcerciseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liftname', models.CharField(max_length=255)),
                ('lift1setwieght', models.SmallIntegerField()),
                ('lift1repnumber', models.SmallIntegerField()),
                ('lift2setwieght', models.SmallIntegerField()),
                ('lift2repnumber', models.SmallIntegerField()),
                ('lift3setwieght', models.SmallIntegerField()),
                ('liftrepnumber', models.SmallIntegerField()),
                ('liftnote', models.CharField(max_length=255)),
                ('excerciseedate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ir0n.excercisedate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'excercisedetail',
            },
        ),
    ]
