# Generated by Django 3.2.4 on 2021-06-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ir0n', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercisedetail',
            old_name='lift1setwieght',
            new_name='lift1setweight',
        ),
        migrations.RenameField(
            model_name='excercisedetail',
            old_name='lift2setwieght',
            new_name='lift2setweight',
        ),
        migrations.RenameField(
            model_name='excercisedetail',
            old_name='lift3setwieght',
            new_name='lift3setweight',
        ),
    ]
